/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softron.census.schema.constant;

import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Mozahid
 */
public enum UrlEnum {
    SUMMARY_OF_MANPOWER_OF_ALL_ORG_TYPE("/summaryofmanpowerofall", "1.SUMMARY OF MANPOWER OF MINISTRIES AND DIVISIONS,DEPARTMENTS AND DIRECTORATES DIV. COM AND DY. COM OFFICES,AUTONOMOUS BODIES AND CORPORATION"),
    BAR_CHART_FOR_MANPOWER_OF_ALL_ORG("/barchartdata", "2.GRAPH SHOWING SANCTIONED,EXISTING AND VACANT MANPOWER OF MINISTRIES AND DIVISIONS,DEPARTMENTS AND DIRECTORATES DIV. COM AND DY. COM OFFICES,AUTONOMOUS BODIES AND CORPORATION"),
    BAR_CHART_FOR_MINISTRIES_AND_DIVISION("/barchartforministriesanddivision", "2.1.GRAPH SHOWING SANCTIONED,EXISTING AND VACANT MANPOWER OF MINISTRIES AND DIVISION"),
    BAR_CHART_FOR_DEPARTMENT_AND_DIRECTORATE("/barchartfordepartmentanddirectorate", "2.2.GRAPH SHOWING SANCTIONED,EXISTING AND VACANT MANPOWER OF DEPARTMENT AND DIRECTORATE"),
    BAR_CHART_FOR_DIVISIONAL_COMM_AND_DEPUTY_COMM("/barchartfordivisionalcommanddeputycomm", "2.3.GRAPH SHOWING SANCTIONED,EXISTING AND VACANT MANPOWER OF DIV. COMM AND DY. COM"),
    BAR_CHART_FOR_AUTONOMOUS_BODIES_AND_CORPORATION("/barchartforautonomousbodiesandcorporation", "2.4.GRAPH SHOWING SANCTIONED,EXISTING AND VACANT MANPOWER OF AUTONOMOUS BODIES AND CORPORATION"),
    CLASS_WISE_BREAKDOWN_OF_CIVIL_OFFICER_AND_STAFF("/civilofficerandstaffreport", "3.CLASS-WISE BREAKDOWN OF CIVIL OFFICERS AND STAFF"),
    CLASS_WISE_STATISTICS_OF_OFFICERS_AND_STAFF_OF_MINISTRY_AND_DIVISION("/classwisestaticsofofficerandstaffofministryanddivision", "4.CLASS-WISE STATISTICS OF OFFICERS AND STAFF OF MINISTRIES AND DIVISION"),
    CLASS_WISE_STATISTICS_OF_OFFICERS_AND_STAFF_OF_DEPARTMENT_AND_DIRECTORATE("/classwisestaticsofofficerandstaffofdepartmentanddirectorate", "5.CLASS-WISE STATISTICS OF OFFICERS AND STAFF OF DEPARTMENTS AND DIRECTORATES"),
    CLASS_WISE_STATISTICS_OF_OFFICERS_AND_STAFF_OF_DIVISIONAL_COMM_AND_DEPUTY_COMM("/classwisestaticsofofficerandstaffofdivisionalcommanddeputycomm", "6.CLASS-WISE STATISTICS OF OFFICERS AND STAFF OF DIV. COMM AND DY. COM OFFICES"),
    CLASS_WISE_STATISTICS_OF_OFFICERS_AND_STAFF_OF_AUTONOMOUS_BODIES_CORPORATION("/classwisestaticsofofficerandstaffofautonomousbodiescorporation", "7.CLASS-WISE STATISTICS OF OFFICERS AND STAFF OF AUTONOMOUS BODIES AND CORPORATIONS"),
    CLASS1_OFFICER_OF_MINISTRIES_AND_DIVISION_BY_PAYSCALE("/class1officerofministriesdivisionbypayscale", "8.STATISTICS OF CLASS-I OFFICERS OF THE MINISTRIES AND DIVISIONS BY NATIONAL PAY SCALE"),
    CLASS1_OFFICER_OF_DEPARTMENT_AND_DIRECTORATE_BY_PAYSCALE("/class1officerofdepartmentanddirectoratepayscale", "9.STATISTICS OF CLASS-I OFFICERS OF THE DEPARTMENT AND DIRECTORATES BY NATIONAL PAY SCALE"),
    CLASS1_OFFICER_OF_DIV_COMM_DEP_COMM_BY_PAYSCALE("/class1officerofdivcommdepcommbypayscale", "10.STATISTICS OF CLASS-I OFFICERS OF DIV. COMM AND DY. COM OFFICES BY NATIONAL PAY SCALE"),
    CLASS1_OFFICER_OF_AUTONOMOUS_BODIES_AND_CORPORATION_PAYSCALE("/class1officerofautonomousbodiesandcorporationpayscale", "11.STATISTICS OF CLASS-I OFFICERS OF AUTONOMOUS BODIES AND CORPORATIONS BY NATIONAL PAY SCALE"),
    CLASS_WISE_STATISTICS_OF_FEMALE_OFFICERS_AND_STAFF("/classwisestaticsoffemaleofficersandstaffdata", "12.CLASS-WISE STATISTICS OF FEMALE OFFICER AND STAFF"),
    CLASS_WISE_STATISTICS_OF_MALE_AND_FEMALE_OFFICER_AND_STAFF_MINISTRY_AND_DIVISION("/classwisestaticsofmaleandfemaleofministryanddivision", "13.CLASS-WISE STATISTICS OF MALE AND FEMALE OFFICER AND STAFF OF MINISTRIES AND DIVISION"),
    CLASS_WISE_STATISTICS_OF_MALE_AND_FEMALE_OFFICER_AND_STAFF_DEPARTMENT_AND_DIRECTORATE("/classwisestaticsofmaleandfemaleofdepartmentanddirectorate", "14.CLASS-WISE STATISTICS OF MALE AND FEMALE OFFICER AND STAFF OF DEPARTMENT AND DIRECTORATES"),
    CLASS_WISE_STATISTICS_OF_MALE_AND_FEMALE_OFFICER_AND_STAFF_DIVISIONAL_COMMISSIONER_AND_DEPUTY_COMMISSIONER("/classwisestaticsofmaleandfemaleofdivisionalcommissioneranddeputycommo", "15.CLASS-WISE STATISTICS OF MALE AND FEMALE OFFICER AND STAFF DIV. COM & DY.COM OFFICES"),
    CLASS_WISE_STATISTICS_OF_MALE_AND_FEMALE_OFFICER_AND_STAFF_AUTONOMOUS_BODIES_CORPORATION("/classwisestaticsofmaleandfemaleofautonomousbodiescorporation", "16.CLASS-WISE STATISTICS OF MALE AND FEMALE OFFICER AND STAFF AUTONOMOUS BODIES CORPORATION"),
    CLASS_WISE_STATISTICS_OF_PROJECT_PERSONNEL("/classwisestaticsofprojectpersonnel", "17.CLASS-WISE STATISTICS OF PROJECT PERSONNEL OF THE GOVERNMENT OF BANGLADESH");

    private UrlEnum(String value, String name) {
        this.value = value;
        this.name = name;
    }

    private String value;

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    private UrlEnum() {
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public static List<UrlEnum> getAllUrl() {
        return Arrays.asList(UrlEnum.values());
    }

}
